[package]
name = "vox_core"
version = "0.1.0"
authors = ["jasperdewinther <31817802+jasperdewinther@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version="0.29", default-features=false}